- name: variables
  hosts: localhost
  vars: #variables declartion
    Course: "Ansible"
    Trainer: "Vishnu"
    Duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
    msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
