- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "4:05AM CST"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}.Timings are: {{timings}}"