- name: variables from arguments
  hosts: localhost
  tasks:
  - name: get from args
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"

#ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password:DevOps321 09-vars-args.yaml -e PERSON=VISHNU -e WISHES=EVENING
#so baiscally in end of the command you to give varibles using -e in each declaring the varibales 
# so basically we are using two varibales and using twice -e
# -e PERSON=VISHNU -e WISHES=EVENING