- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'HI, this is from command module' > /tmp/command.txt "

  - name: shell module
    ansible.builtin.command: "echo 'HI, this is from shell module' > /tmp/shell.txt "

# simple commands without the need of shell  variable, environment  and features like redirections, pipes , & go fro command module

# if we need to run complex commands or script go for shell module.
