172.31.28.231
[web]
172.31.28.234 ansible_user=ec2-user ansible_ssh_private_key_file=/path/to/node-key.pem

#[web:vars]
#DB_URL="http://172.31.28.234"

[localhost]
localhost ansible_connection=local

[localhost:vars]
Course="DevOps with AWS"
Trainer="Vishnu"
Duration="120hrs"
#WISHES="Morning from inventory"

[db]
172.31.28.232

[app]
172.31.28.233

[all:children]
web
db
app